In [90]:
!pip install imblearn

In [91]:
import pandas as pd
import csv
import sklearn
import numpy as np
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import NearMiss
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE 

In [92]:
from nltk.classify import SklearnClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
#metrics
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [93]:
df_total = pd.read_csv("third_df_rmsw.csv") 

In [94]:
q = df_total['polarity'].astype(int)
#y = np.where((q==2) | (q == 1), 0, 1)
y = np.where(q == 3, 0, 1) #convert polarities binary: 0-neutral/1-polar
X = df_total.drop("polarity",1) 

In [95]:
ts=0.3
rs=42
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = ts, random_state = rs)

In [96]:

print("Before OverSampling, counts of label '1': {}".format(sum(y_train == 1))) 
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train == 0)))
sm = SMOTE(random_state = 2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel()) 
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0))) 

Before OverSampling, counts of label '1': 2357
Before OverSampling, counts of label '0': 7522 

After OverSampling, counts of label '1': 7522
After OverSampling, counts of label '0': 7522


In [97]:
print("Before Undersampling, counts of label '1': {}".format(sum(y_train == 1))) 
print("Before Undersampling, counts of label '0': {} \n".format(sum(y_train == 0))) 
nr = NearMiss() 
X_train_miss, y_train_miss = nr.fit_resample(X_train, y_train) 
print("After Undersampling, counts of label '1': {}".format(sum(y_train_miss == 1))) 
print("After Undersampling, counts of label '0': {}".format(sum(y_train_miss == 0))) 


Before Undersampling, counts of label '1': 2357
Before Undersampling, counts of label '0': 7522 

After Undersampling, counts of label '1': 2357
After Undersampling, counts of label '0': 2357


In [98]:
undersample = RandomUnderSampler(sampling_strategy=0.5)
X_over, y_over = undersample.fit_resample(X_train, y_train)
print(len(X_over))
print(len(y_over))

7071
7071


In [99]:
svc = SVC(class_weight="balanced", gamma="scale")
#svc.fit(X_train, y_train)
#svc.fit(X_over, y_over)
svc.fit(X_train_miss, y_train_miss)
svc_predict = svc.predict(X_test)

print("SVC:\n")
print(classification_report(y_test, svc_predict))
print(confusion_matrix(y_test, svc_predict))

SVC:

              precision    recall  f1-score   support

           0       0.82      0.67      0.74      3205
           1       0.34      0.53      0.42      1030

    accuracy                           0.64      4235
   macro avg       0.58      0.60      0.58      4235
weighted avg       0.70      0.64      0.66      4235

[[2159 1046]
 [ 481  549]]


In [104]:
rf = RandomForestClassifier(n_estimators=100, class_weight="balanced")
#rf.fit(X_train, y_train)
#rf.fit(X_train_miss, y_train_miss)
rf.fit(X_over, y_over)
rf_predict = rf.predict(X_test)

print("RandomForestClassifier:\n")
print(classification_report(y_test, rf_predict))
print(confusion_matrix(y_test, rf_predict))

RandomForestClassifier:

              precision    recall  f1-score   support

           0       0.82      0.62      0.71      3205
           1       0.33      0.58      0.42      1030

    accuracy                           0.61      4235
   macro avg       0.58      0.60      0.57      4235
weighted avg       0.70      0.61      0.64      4235

[[1996 1209]
 [ 431  599]]


In [85]:
df_total = df_total.drop("isSubject", 1)
#df_total = df_total.drop("isObject", 1)
ts=0.3
rs=0
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = ts, random_state = rs)
svc = SVC()
svc.fit(X_train, y_train)
#svc.fit(X_train_res, y_train_res.ravel())
svc_predict = svc.predict(X_test)

print("SVC:\n")
print(classification_report(y_test, svc_predict))
print(confusion_matrix(y_test, svc_predict))

SVC:

              precision    recall  f1-score   support

           0       0.76      0.98      0.86      3176
           1       0.56      0.07      0.13      1059

    accuracy                           0.75      4235
   macro avg       0.66      0.53      0.49      4235
weighted avg       0.71      0.75      0.67      4235

[[3116   60]
 [ 982   77]]
